# Generated by Django 3.2.5 on 2021-08-11 12:52

from django.db import migrations, models
import world_traveller.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[world_traveller.core.validators.validate_text_starts_with_capital])),
                ('location', models.CharField(max_length=50, validators=[world_traveller.core.validators.validate_text_starts_with_capital])),
                ('description', models.TextField(validators=[world_traveller.core.validators.validate_text_starts_with_capital])),
                ('image', models.ImageField(upload_to='places')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
